export const routeTitleMap: Record<string, string> = {
  '/': 'Home',
  '/Home': 'Home',
  '/Policy': 'Policy',
  '/Create': 'Create',
  '/Create/:char_uuid': 'Edit Character',
  '/Subscription': 'Subscription',
  '/Archive': 'Archive',
  '/Profile': 'Profile',
  '/Profile/:creator_uuid': 'Profile',
  '/Chat/:chat_uuid': 'Chat',
  '/Settings': 'Settings',
  '/ContentPolicy': 'Content Policy',
  '/docs': 'Docs',
  '/docs/:doc_name': 'Docs',
  '/Admin': 'Admin',
  '/character/:char_uuid': 'Character',
  '/Blocked': 'Blocked',
  '*': 'Page Not Found',
};
