name = "pyrenzai"
compatibility_date = "2025-07-05"

pages_build_output_dir = "./dist"

[vars]
VITE_SERVER_API_URL = "https://pyrenzaiserver-p44g.onrender.com" # Required by the application, if you wish to run this in cloudflare, feel free to do so, else manually copy this env to your env file.