name = "pyrenzai"
compatibility_date = "2025-07-05"

pages_build_output_dir = "./dist"

[vars]
VITE_SERVER_API_URL_1 = "https://s1.pyrenzai.com"
VITE_SERVER_API_URL_2 = "https://s2.pyrenzai.com"
BUN_VERSION = "latest"

[build]
command = "bun run build"
